# Generated by Django 3.1.6 on 2021-02-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_kg',
            field=models.CharField(max_length=50, verbose_name='Суроо'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ru',
            field=models.CharField(max_length=50, verbose_name='Вопрос'),
        ),
    ]
