# Generated by Django 3.1.6 on 2021-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210202_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='Тело поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=models.TextField(max_length=1500, null=True, verbose_name='Тело поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
